---
name: DBM-Deep
version: 1.0004
author: []
abstract: A pure perl multi-level hash/array DBM that supports transactions
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Clone: 0.01
  Digest::MD5: 1.00
  Fcntl: 0.01
  FileHandle::Fmode: 0.05
  Scalar::Util: 1.14
  perl: 5.006_000
build_requires:
  File::Path: 0.01
  File::Temp: 0.01
  IO::Scalar: 0.01
  Test::Deep: 0.095
  Test::Exception: 0.21
  Test::More: 0.47
  Test::Warn: 0.08
provides:
  DBM::Deep:
    file: lib/DBM/Deep.pm
    version: 1.0004
  DBM::Deep::Array:
    file: lib/DBM/Deep/Array.pm
    version: 1.0004
  DBM::Deep::Engine:
    file: lib/DBM/Deep/Engine.pm
    version: 1.0004
  DBM::Deep::Engine::Sector:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Engine::Sector::BucketList:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Engine::Sector::Data:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Engine::Sector::Index:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Engine::Sector::Null:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Engine::Sector::Reference:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Engine::Sector::Scalar:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::File:
    file: lib/DBM/Deep/File.pm
    version: 1.0004
  DBM::Deep::Hash:
    file: lib/DBM/Deep/Hash.pm
    version: 1.0004
  DBM::Deep::Iterator:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Iterator::BucketList:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Iterator::Index:
    file: lib/DBM/Deep/Engine.pm
  DBM::Deep::Null:
    file: lib/DBM/Deep/Engine.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
